/**
 * Builds Levee orders and taker data with the 1inch SDKs and writes them to
 * contracts/test/fixtures/sdk-vectors.json. contracts/test/SdkParity.t.sol rebuilds the same
 * values with swap-vm's Solidity libraries and requires identical bytes.
 *
 *   npx tsx src/aqua/exportSdkVectors.ts
 */
import { writeFileSync, mkdirSync } from "fs";
import { getAddress, keccak256, toBytes } from "viem";
import addresses from "../../config/addresses.json" with { type: "json" };
import { buildLeveeOrder, buildLeveeProgram, encodeLeveeParams, sellPtTakerTraits, strategyHash, type LeveeParams } from "./levee.js";

const label = (s: string) => getAddress(`0x${keccak256(toBytes(s)).slice(-40)}`);

const maker = label("levee-sdk-vector-maker");
const quoter = label("levee-sdk-vector-quoter");

const params: LeveeParams = {
  pt: getAddress(addresses.pendle.pt),
  sy: getAddress(addresses.pendle.sy),
  market: getAddress(addresses.pendle.market),
  refYieldWad: 105_830_000_000_000_000n,
  discountBps: 10,
  maxPtPerTrade: 5_000_000n * 10n ** 6n,
  minSyRate: 1_085_832n,
};

const order = buildLeveeOrder(maker, quoter, params);
const built = order.build();

const takerCases = [
  { name: "exactInMinOut", exactIn: true, threshold: 88_000n * 10n ** 18n, pullPtFromTaker: true },
  { name: "exactOutMaxIn", exactIn: false, threshold: 60_000n * 10n ** 6n, pullPtFromTaker: true },
  { name: "flashCallback", exactIn: true, threshold: 0n, pullPtFromTaker: false, callbackData: "0xabcdef" as const },
];

const vectors = {
  note: "Generated by src/aqua/exportSdkVectors.ts with @1inch/swap-vm-sdk; checked by SdkParity.t.sol",
  maker,
  quoter,
  params: {
    ...params,
    refYieldWad: params.refYieldWad.toString(),
    maxPtPerTrade: params.maxPtPerTrade.toString(),
    minSyRate: params.minSyRate.toString(),
  },
  encodedParams: encodeLeveeParams(params),
  program: buildLeveeProgram(quoter, params).toString(),
  orderTraits: `0x${built.traits.toString(16).padStart(64, "0")}`,
  orderData: built.data,
  strategyHash: strategyHash(order),
  taker: takerCases.map((c) => ({
    ...c,
    threshold: c.threshold.toString(),
    takerData: sellPtTakerTraits(c).encode().toString(),
  })),
};

mkdirSync("contracts/test/fixtures", { recursive: true });
writeFileSync("contracts/test/fixtures/sdk-vectors.json", JSON.stringify(vectors, null, 2) + "\n");
console.log(`strategy hash ${vectors.strategyHash}`);
console.log(`program       ${vectors.program}`);
console.log("wrote contracts/test/fixtures/sdk-vectors.json");
