/**
 * Builds Wamia orders and taker data with the 1inch SDKs and writes them to
 * contracts/test/fixtures/sdk-vectors.json. contracts/test/SdkParity.t.sol rebuilds the same
 * values with swap-vm's Solidity libraries and requires identical bytes.
 *
 *   npx tsx src/aqua/exportSdkVectors.ts
 */
import { writeFileSync, mkdirSync } from "fs";
import { getAddress, keccak256, toBytes } from "viem";
import addresses from "../../config/addresses.json" with { type: "json" };
import {
  buildWamiaOrder,
  buildWamiaProgram,
  encodeWamiaParams,
  sellPtTakerTraits,
  strategyHash,
  type WamiaGuards,
  type WamiaParams,
} from "./wamia.js";

const label = (s: string) => getAddress(`0x${keccak256(toBytes(s)).slice(-40)}`);

const maker = label("wamia-sdk-vector-maker");
const quoter = label("wamia-sdk-vector-quoter");

const params: WamiaParams = {
  pt: getAddress(addresses.pendle.pt),
  sy: getAddress(addresses.pendle.sy),
  market: getAddress(addresses.pendle.market),
  curvePool: getAddress(addresses.reusdMarketPrice.curvePool),
  refYieldWad: 105_830_000_000_000_000n,
  discountMinBps: 10,
  discountMaxBps: 60,
  shippedSy: 5_000_000n * 10n ** 18n,
  minSyRate: 1_085_832n,
  maxDepegBps: 100,
  maxDeviationBps: 450,
  flags: 0,
};

const order = buildWamiaOrder(maker, quoter, params);
const built = order.build();

const guards: WamiaGuards = {
  rateGuard: label("wamia-sdk-vector-rate-guard"),
  rateGuardParams: {
    sy: params.sy,
    rateAtShip: 1_096_798n,
    shipTimestamp: 1_787_632_115n,
    maxDropBps: 0,
    minElapsed: 3 * 86_400,
    refYieldWad: params.refYieldWad,
    maxYieldGapBps: 1000,
  },
  spendLimit: label("wamia-sdk-vector-spend-limit"),
  spendLimitParams: { shippedSy: params.shippedSy, windowSec: 12, minCapBps: 2000, horizonSec: 30 * 86_400, expiry: 1_796_860_800n },
};
const guardedOrder = buildWamiaOrder(maker, quoter, params, guards);

const takerCases = [
  { name: "exactInMinOut", exactIn: true, threshold: 88_000n * 10n ** 18n, pullPtFromTaker: true },
  { name: "exactOutMaxIn", exactIn: false, threshold: 60_000n * 10n ** 6n, pullPtFromTaker: true },
  { name: "flashCallback", exactIn: true, threshold: 0n, pullPtFromTaker: false, callbackData: "0xabcdef" as const },
];

const vectors = {
  note: "Generated by src/aqua/exportSdkVectors.ts with @1inch/swap-vm-sdk; checked by SdkParity.t.sol",
  maker,
  quoter,
  params: {
    ...params,
    refYieldWad: params.refYieldWad.toString(),
    shippedSy: params.shippedSy.toString(),
    minSyRate: params.minSyRate.toString(),
  },
  encodedParams: encodeWamiaParams(params),
  program: buildWamiaProgram(quoter, params).toString(),
  orderTraits: `0x${built.traits.toString(16).padStart(64, "0")}`,
  orderData: built.data,
  strategyHash: strategyHash(order),
  guarded: {
    rateGuard: guards.rateGuard,
    rateGuardParams: {
      ...guards.rateGuardParams,
      rateAtShip: guards.rateGuardParams.rateAtShip.toString(),
      shipTimestamp: guards.rateGuardParams.shipTimestamp.toString(),
      refYieldWad: guards.rateGuardParams.refYieldWad.toString(),
    },
    spendLimit: guards.spendLimit,
    spendLimitParams: {
      ...guards.spendLimitParams,
      shippedSy: guards.spendLimitParams.shippedSy.toString(),
      expiry: guards.spendLimitParams.expiry.toString(),
    },
    program: buildWamiaProgram(quoter, params, guards).toString(),
    strategyHash: strategyHash(guardedOrder),
  },
  taker: takerCases.map((c) => ({
    ...c,
    threshold: c.threshold.toString(),
    takerData: sellPtTakerTraits(c).encode().toString(),
  })),
};

mkdirSync("contracts/test/fixtures", { recursive: true });
writeFileSync("contracts/test/fixtures/sdk-vectors.json", JSON.stringify(vectors, null, 2) + "\n");
console.log(`strategy hash ${vectors.strategyHash}`);
console.log(`program       ${vectors.program}`);
console.log("wrote contracts/test/fixtures/sdk-vectors.json");
